export default {
  jsUrl:   "",
  features : {
    'home:recentArticles' : false,
    'article:scroll_depth' : true,
    'article:timeOnPage' : true,
    'article:pageViews' : true,
    'article:socialUsers' : false,
    'article:readTimes' : false,
    'article:timeSincePublished' : true,
    'article:channels' : true,
    'article:referrers' : true,
    'article:referrers:internalRefTypes' : false,
    'article:devices' : true,
    'article:locations' : true,
    'article:bounceRate' : true,
    'article:who' : true,
    'article:where' : true,
    'article:interact' : true,
    'article:subscription' : true,
    'article:social_shares' : true,
    'article:total_links_clicked' : true,
    'article:comments_posted_total' : true,
    'article:modifier:filters:UserCohort' : true,
    'article:modifier:filters:Referrers' : true,
    'article:modifier:filters:Region' : true,
    'article:modifier:filters:Device' : true,
    'article:modifier:DateRange' : true,
  }
};
