export default {
  jsUrl:   "",
  features : {
    'home:recentArticles' : false,
    'article:title' : true,
    'article:wordCount' : false,
    'article:imageCount' : false,
    'article:bodyLinksCount' : false,
    'article:timeOnPage' : true,
    'article:pageViews' : true,
    'article:socialReaders' : false,
    'article:readTimes' : true,
    'article:channels' : true,
    'article:devices' : false,
    'article:modifier' : true,
    'article:modifier:comparator' : true,
    'article:modifier:filters' : false,
    'article:modifier:DateRange' : true,
    'playground:header' : true,
    'playground:logo' : true,
    'playground:search' : true,
    'playground:singlemetric' : true,
    'playground:modifier' : true,
    'playground:modifier:comparator' : true,
    'playground:modifier:filters' : true,
    'playground:modifier:DateRange' : true,
    'playground:piechart' : true,
    'playground:linechart' : true,
    'playground:barchart' : true,
    'playground:columnchart' : true,
    'playground:map' : true
  }
};
